version: '3.5'

services:

  angular-app:
    container_name: app-angular
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:80'